# Generated by Django 5.2.1 on 2025-05-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(verbose_name="Açıklama")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Fiyat"
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("ARSA", "Arsa"),
                            ("KONUT", "Konut"),
                            ("ISYERI", "İşyeri"),
                            ("TARLA", "Tarla"),
                            ("DIGER", "Diğer"),
                        ],
                        max_length=10,
                        verbose_name="Emlak Tipi",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("SATILIK", "Satılık"), ("KIRALIK", "Kiralık")],
                        max_length=10,
                        verbose_name="İlan Tipi",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Emlak",
                "verbose_name_plural": "Emlaklar",
            },
        ),
        migrations.CreateModel(
            name="CommercialProperty",
            fields=[
                (
                    "property_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="properties.property",
                    ),
                ),
                (
                    "square_meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="m²"
                    ),
                ),
                (
                    "heating_status",
                    models.CharField(max_length=100, verbose_name="Isıtma Durumu"),
                ),
                ("floor_count", models.PositiveIntegerField(verbose_name="Kat Sayısı")),
                (
                    "floor_location",
                    models.PositiveIntegerField(verbose_name="Bulunduğu Kat"),
                ),
            ],
            options={
                "verbose_name": "İşyeri",
                "verbose_name_plural": "İşyerleri",
            },
            bases=("properties.property",),
        ),
        migrations.CreateModel(
            name="LandProperty",
            fields=[
                (
                    "property_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="properties.property",
                    ),
                ),
                (
                    "zoning_status",
                    models.CharField(max_length=100, verbose_name="İmar Durumu"),
                ),
                (
                    "square_meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="m²"
                    ),
                ),
                (
                    "price_per_square_meter",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="m² Fiyatı"
                    ),
                ),
                (
                    "block_number",
                    models.CharField(max_length=50, verbose_name="Ada No"),
                ),
                (
                    "parcel_number",
                    models.CharField(max_length=50, verbose_name="Parsel No"),
                ),
                (
                    "credit_eligibility",
                    models.BooleanField(default=True, verbose_name="Krediye Uygunluk"),
                ),
                (
                    "deed_status",
                    models.CharField(max_length=100, verbose_name="Tapu Durumu"),
                ),
                (
                    "exchange_possible",
                    models.BooleanField(default=False, verbose_name="Takas"),
                ),
            ],
            options={
                "verbose_name": "Arsa/Tarla",
                "verbose_name_plural": "Arsa/Tarlalar",
            },
            bases=("properties.property",),
        ),
        migrations.CreateModel(
            name="ResidentialProperty",
            fields=[
                (
                    "property_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="properties.property",
                    ),
                ),
                (
                    "gross_square_meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Brüt m²"
                    ),
                ),
                (
                    "net_square_meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Net m²"
                    ),
                ),
                ("room_count", models.PositiveIntegerField(verbose_name="Oda Sayısı")),
                ("floor_count", models.PositiveIntegerField(verbose_name="Kat Sayısı")),
                (
                    "floor_location",
                    models.PositiveIntegerField(verbose_name="Bulunduğu Kat"),
                ),
                (
                    "heating_system",
                    models.CharField(max_length=100, verbose_name="Isıtma Sistemi"),
                ),
                (
                    "bathroom_count",
                    models.PositiveIntegerField(verbose_name="Banyo Sayısı"),
                ),
                (
                    "kitchen_type",
                    models.CharField(max_length=100, verbose_name="Mutfak Tipi"),
                ),
                (
                    "has_balcony",
                    models.BooleanField(default=False, verbose_name="Balkon"),
                ),
                (
                    "balcony_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Balkon Sayısı"
                    ),
                ),
                (
                    "has_parking",
                    models.BooleanField(default=False, verbose_name="Otopark"),
                ),
                (
                    "parking_type",
                    models.CharField(
                        blank=True,
                        choices=[("ACIK", "Açık"), ("KAPALI", "Kapalı")],
                        max_length=50,
                        null=True,
                        verbose_name="Otopark Tipi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konut",
                "verbose_name_plural": "Konutlar",
            },
            bases=("properties.property",),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="properties/", verbose_name="Resim"),
                ),
                (
                    "is_main",
                    models.BooleanField(default=False, verbose_name="Ana Resim"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emlak Resmi",
                "verbose_name_plural": "Emlak Resimleri",
            },
        ),
    ]
